title: rimaz
email: rimazmo18@gmail.com
description: "this this blog to document my journey."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rimaz" # the base hostname & protocol for your site, e.g. http://example.com
twitter: 
github:  rimazmo
mail: rimazmo18@gmail.com
linkedin: 

# site settings 
contact: true
about: true
version: v1.1.0

# Theme settings 

edit-date: false # show the date of last edit on pages
default-theme: sandcastle # pick which theme loads by default

# post settings 

tags: foo bar
# development settings 

developer-controls: false # show developer specefic tips

# Build settings
theme: jek
plugins:
  - jekyll-feed


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class : 'syntax'

